language: python
  
branches:
  only:
  - master

env:
  TEST: west
  
jobs:
  include:
    - stage: test-${TRAVIS_BUILD_ID}
      script: 
        - ls -l
        - python test.py
        - echo ${ENVO}
        - echo $ENVT
        - echo $TRAVIS_BUILD_DIR
        - echo $TEST
    - stage: test-${ENVT}
      script: 
        - ls -l
