language: python
python:
  - "2.6"
  - "2.7"
  
 branches:
  only:
  - master
  - py-test-b1
  
# command to install dependencies
install:
  - pip install requests
# command to run tests
script: 
    - ls -l
    - python test.py
